ytbatch: print summary

diff --git a/ytbatch b/ytbatch
--- a/ytbatch
+++ b/ytbatch
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
-depend mktemp mkdir xargs xclip yt-dlp || exit
+depend mktemp mkdir xargs xclip yt-dlp cat wc tput mv || exit
 
 DIR=$(mktemp -d -t "${0##*/}-$$"-ytdl-XXXXX)
 QUEUE2="$DIR"/queue2
 INFODIR="$DIR"/info
 FAILQUEUE="$DIR"/fail_queue
 FIFODIR="$DIR"/fifo
+SUMMARY="$DIR"/summary
 
 cleanup() {
 	jobs > /dev/null
@@ -100,10 +101,12 @@ while true; do
 			then
 				rm "$logfile"
 				echo -e '\033[92mDone'
+				printf '\033[1;92m    OK\033[0m %s\n' "$(yt-dlp --load-info-json "$info" --no-warnings --no-sponsorblock --print title)" >> "$SUMMARY"
 				exit 0
 			else
 				[[ -d "$DIR" ]] && echo "$format" "$info" >> "$FAILQUEUE"
 				echo -e '\033[91mFailed'
+				printf '\033[1;91mFAILED\033[0m %s\n' "$(yt-dlp --load-info-json "$info" --no-warnings --no-sponsorblock --print title)" >> "$SUMMARY"
 				exit 1
 			fi | tee "$fifofile" | while read -r; do
 				echo -ne "\033[$((LINE+1));H\033[2K${REPLY:0:$(eval 'tput cols')}\033[0m"
@@ -135,6 +138,9 @@ while true; do
 	wait
 
 	printf '\033[%d;H' "${MAX_LINE:=$LINE}"
+
+	echo "Summary:"
+	cat "$SUMMARY"
 
 	if [[ -r "$FAILQUEUE" ]] && (( $(wc -l < "$FAILQUEUE") > 0 )) && read -rN1 -p "$(wc -l < "$FAILQUEUE") failed, retry?"; then
 		case "$REPLY" in
