ytbatch: allow retries

diff --git a/ytbatch b/ytbatch
--- a/ytbatch
+++ b/ytbatch
@@ -5,6 +5,7 @@ depend mktemp mkdir xargs xclip yt-dlp || exit
 DIR=$(mktemp -d -t "${0##*/}-$$"-ytdl-XXXXX)
 QUEUE2="$DIR"/queue2
 INFODIR="$DIR"/info
+FAILQUEUE="$DIR"/fail_queue
 
 cleanup() {
 	jobs -pr | xargs -r kill
@@ -66,63 +67,76 @@ done
 
 [[ -r "$QUEUE2" ]] || exit
 
-clear -x
+while true; do
+	clear -x
 
-declare -A LINE_BUSY
-declare -A PID_LINE
-declare -a FINISHED
-max_line=1
+	unset LINE_BUSY
+	declare -A LINE_BUSY
+	unset PID_LINE
+	declare -A PID_LINE
+	unset FINISHED
+	declare -a FINISHED
+	max_line=1
 
-while read -r format info; do
-	line=1
-	while [[ -n "${LINE_BUSY[$line]}" ]]; do
-		line=$((line+2))
-		if ((line > max_line)); then
-			max_line=$line
-		fi
-		if ((line+2 >= $(tput lines))); then
-			notify-send "$line"
-			for pid in "${FINISHED[@]}"; do
+	while read -r format info; do
+		line=1
+		while [[ -n "${LINE_BUSY[$line]}" ]]; do
+			line=$((line+2))
+			if ((line > max_line)); then
+				max_line=$line
+			fi
+			if ((line+2 >= $(tput lines))); then
+				for pid in "${FINISHED[@]}"; do
+					unset "LINE_BUSY[${PID_LINE[$pid]}]"
+					unset "PID_LINE[$pid]"
+				done
+			fi
+		done
+
+		logfile=$(yt-dlp --load-info-json "$info" --no-sponsorblock --print filename)
+		logfile=${logfile%.*}.log
+
+		printf '\033[%d;H\033[2K%s' "$line" "$(yt-dlp --load-info-json "$info" --no-sponsorblock --print "%(title)s -- $format")"
+
+		(
+			set -eo pipefail
+			if yt-dlp --load-info-json "$info" -f "$format" \
+				--newline --progress --progress-delta 1 --color always \
+				--no-simulate --print "Starting download for %(id)s" --print "after_move:%(id)s done" \
+				--quiet --verbose 2> "$logfile" && [ "$(shuf -i 0-1 -n1)" == 0 ]
+			then
+				rm "$logfile"
+				sleep 1
+				exit 0
+			else
+				echo Failed
+				echo "$format" "$info" >> "$FAILQUEUE"
+				sleep 1
+				exit 1
+			fi | xargs -L1 echo -ne "\033[$((line+1));H\033[2K"
+		) &
+		PID_LINE[$!]=$line
+		LINE_BUSY[$line]=1
+
+		while (( $(jobs -pr | wc -l) >= 2)); do
+			if wait -np pid; then
 				unset "LINE_BUSY[${PID_LINE[$pid]}]"
 				unset "PID_LINE[$pid]"
-			done
-		fi
-	done
+			fi
+			FINISHED+=("$pid")
+		done
+		sleep 0.1
+	done < "$QUEUE2"
 
-	logfile=$(yt-dlp --load-info-json "$info" --no-sponsorblock --print filename)
-	logfile=${logfile%.*}.log
+	wait
 
-	printf '\033[%d;H\033[2K%s' "$line" "$(yt-dlp --load-info-json "$info" --no-sponsorblock --print "%(title)s -- $format")"
+	printf '\033[%d;H' "$((max_line+2))"
 
-	(
-		set -eo pipefail
-		if yt-dlp --load-info-json "$info" -f "$format" \
-			--newline --progress --progress-delta 1 --color always \
-			--no-simulate --print "Starting download for %(id)s" --print "after_move:%(id)s done" \
-			--quiet --verbose 2> "$logfile"
-		then
-			rm "$logfile"
-			sleep 1
-			exit 0
-		else
-			echo Failed
-			sleep 1
-			exit 1
-		fi | xargs -L1 echo -ne "\033[$((line+1));H\033[2K"
-	) &
-	PID_LINE[$!]=$line
-	LINE_BUSY[$line]=1
-
-	while (( $(jobs -pr | wc -l) >= 2)); do
-		if wait -np pid; then
-			unset "LINE_BUSY[${PID_LINE[$pid]}]"
-			unset "PID_LINE[$pid]"
-		fi
-		FINISHED+=("$pid")
-	done
-	sleep 0.1
-done < "$QUEUE2"
-
-wait
-
-printf '\033[%d;H' "$((max_line+2))"
+	if [[ -r "$FAILQUEUE" ]] && (( $(wc -l < "$FAILQUEUE") > 0 )) && read -rN1 -p "$(wc -l < "$FAILQUEUE") failed, retry?"; then
+		case "$REPLY" in
+			y|Y) mv -f "$FAILQUEUE" "$QUEUE2"; continue;;
+			*);;
+		esac
+	fi
+	break
+done
